-- MySQL Script generated by MySQL Workbench
-- 12/07/15 14:37:25
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema wds_di
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `wds_di` ;

-- -----------------------------------------------------
-- Schema wds_di
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wds_di` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `wds_di` ;

-- -----------------------------------------------------
-- Table `UZYTKOWNICY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UZYTKOWNICY` ;

CREATE TABLE IF NOT EXISTS `UZYTKOWNICY` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `LOGIN` VARCHAR(20) NOT NULL COMMENT '',
  `HASLO` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC)  COMMENT '',
  UNIQUE INDEX `nazwa_UNIQUE` (`LOGIN` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ODDZIAL`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ODDZIAL` ;

CREATE TABLE IF NOT EXISTS `ODDZIAL` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `NAZWA` VARCHAR(25) NOT NULL COMMENT '',
  `NUMER` VARCHAR(10) NOT NULL COMMENT '',
  `TATUAZ` VARCHAR(5) NOT NULL COMMENT '',
  `ADRES` VARCHAR(60) NOT NULL COMMENT '',
  `TELEFON` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC)  COMMENT '',
  UNIQUE INDEX `nazwa_UNIQUE` (`NAZWA` ASC)  COMMENT '',
  UNIQUE INDEX `TATUAZ_UNIQUE` (`TATUAZ` ASC)  COMMENT '',
  UNIQUE INDEX `NUMER_UNIQUE` (`NUMER` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `U_O`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `U_O` ;

CREATE TABLE IF NOT EXISTS `U_O` (
  `U_ID` INT UNSIGNED NOT NULL COMMENT '',
  `O_ID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`U_ID`, `O_ID`)  COMMENT '',
  INDEX `fk_uzytkownicy_has_oddzial_oddzial1_idx` (`O_ID` ASC)  COMMENT '',
  INDEX `fk_uzytkownicy_has_oddzial_uzytkownicy_idx` (`U_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_uzytkownicy_has_oddzial_uzytkownicy`
    FOREIGN KEY (`U_ID`)
    REFERENCES `UZYTKOWNICY` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_uzytkownicy_has_oddzial_oddzial1`
    FOREIGN KEY (`O_ID`)
    REFERENCES `ODDZIAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HODOWCA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HODOWCA` ;

CREATE TABLE IF NOT EXISTS `HODOWCA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `IMIE` VARCHAR(20) NULL COMMENT '',
  `NAZWISKO` VARCHAR(45) NOT NULL COMMENT '',
  `TELEFON` VARCHAR(20) NOT NULL COMMENT '',
  `ADRES` VARCHAR(60) NOT NULL COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC)  COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HODOWLA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HODOWLA` ;

CREATE TABLE IF NOT EXISTS `HODOWLA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `NAZWA` VARCHAR(50) NOT NULL COMMENT '',
  `O_ID` INT UNSIGNED NOT NULL COMMENT '',
  `H_ID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `id_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_hodowla_oddzial1_idx` (`O_ID` ASC)  COMMENT '',
  INDEX `fk_HODOWLA_HODOWCA1_idx` (`H_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_hodowla_oddzial1`
    FOREIGN KEY (`O_ID`)
    REFERENCES `ODDZIAL` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HODOWLA_HODOWCA1`
    FOREIGN KEY (`H_ID`)
    REFERENCES `HODOWCA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MIOT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `MIOT` ;

CREATE TABLE IF NOT EXISTS `MIOT` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `URODZONY` DATE NOT NULL COMMENT '',
  `ZNAKOWANY` DATE NOT NULL COMMENT '',
  `POZYCJA` VARCHAR(20) NOT NULL COMMENT '',
  `H_ID` INT UNSIGNED NOT NULL COMMENT '',
  INDEX `fk_MIOT_HODOWLA1_idx` (`H_ID` ASC)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  CONSTRAINT `fk_MIOT_HODOWLA1`
    FOREIGN KEY (`H_ID`)
    REFERENCES `HODOWLA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FCI`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `FCI` ;

CREATE TABLE IF NOT EXISTS `FCI` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `NAZWA` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  UNIQUE INDEX `NAZWA_UNIQUE` (`NAZWA` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RASA`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `RASA` ;

CREATE TABLE IF NOT EXISTS `RASA` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `NAZWA` VARCHAR(50) NOT NULL COMMENT '',
  `FCI_ID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  UNIQUE INDEX `NAZWA_UNIQUE` (`NAZWA` ASC)  COMMENT '',
  INDEX `fk_RASA_FCI1_idx` (`FCI_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_RASA_FCI1`
    FOREIGN KEY (`FCI_ID`)
    REFERENCES `FCI` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PIES`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `PIES` ;

CREATE TABLE IF NOT EXISTS `PIES` (
  `ID` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  `SUKA` TINYINT(1) NULL COMMENT '',
  `IMIĘ` VARCHAR(20) NULL COMMENT '',
  `OZNACZENIE` VARCHAR(15) NOT NULL COMMENT '',
  `OJCIEC` VARCHAR(80) NOT NULL COMMENT '',
  `MATKA` VARCHAR(80) NOT NULL COMMENT '',
  `M_ID` INT UNSIGNED NOT NULL COMMENT '',
  `R_ID` INT UNSIGNED NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  UNIQUE INDEX `OZNACZENIE_UNIQUE` (`OZNACZENIE` ASC)  COMMENT '',
  INDEX `fk_PIES_MIOT1_idx` (`M_ID` ASC)  COMMENT '',
  INDEX `fk_PIES_RASA1_idx` (`R_ID` ASC)  COMMENT '',
  CONSTRAINT `fk_PIES_MIOT1`
    FOREIGN KEY (`M_ID`)
    REFERENCES `MIOT` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PIES_RASA1`
    FOREIGN KEY (`R_ID`)
    REFERENCES `RASA` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
